[clog]
outfile = "CHANGELOG.md"
from-latest-tag = true

[sections]
Performance = ["perf"]
Enhancement = ["enhance"]
Documentation = ["docs"]
Deprecations = ["depr"]
Examples = ["examples"]
CI = ["ci"]
Utils = ["utils"]
