[workspace]
members = [
  "libtdengine"
]
[package]
name = "bailongma"
version = "0.1.0"
authors = ["Huo Linhe <linhehuo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1"
r2d2 = "0.8"
anyhow = "1.0.40"
actix-web = "3.3.2"
snap = "1"
bytes = "*"
prost = "0.7"
prost-types = "0.7"
futures = "0.3.13"
env_logger = "*"
libtdengine = { path = "./libtdengine", features = ["r2d2"] }
lru = "0.6.5"
md-5 = "0.9.1"
itertools = "0.10"
log = "*"
[build-dependencies]
prost-build = "0.7"
anyhow = "1.0.40"

[dev-dependencies]
hex-literal = "0.3"
