pre-release-hook = ["./.github/clog.sh"]
exclude-paths = ["/README.md", "/tests/**", "/examples/**"]
post-release-commit-message = "chore(next): start next dev iteration {{version}}"
pre-release-commit-message = "release: {{version}}"
